<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{{ $typeLabel }} Report</title>
<style>
  * { margin: 0; padding: 0; }
  body { font-family: 'DejaVu Sans', Arial, sans-serif; font-size: 11px; color: #1a1a2e; }

  .header { padding: 14px 28px; border-bottom: 2px solid #185FA5; }
  .header table { width: 100%; }
  .header td.logo-cell { width: 50%; vertical-align: middle; }
  .header td.title-cell { width: 50%; text-align: right; vertical-align: middle; }
  .report-title { font-size: 18px; font-weight: bold; color: #185FA5; }
  .report-sub   { font-size: 9px; color: #888; margin-top: 2px; }

  .meta { background: #f4f6fa; padding: 10px 28px; border-bottom: 1px solid #ddd; }
  .meta table { width: 100%; }
  .meta td { vertical-align: top; padding-right: 10px; }
  .meta-label { font-size: 8px; font-weight: bold; text-transform: uppercase; color: #999; }
  .meta-value { font-size: 11px; font-weight: bold; color: #1a1a2e; }

  .summary { padding: 12px 28px; border-bottom: 1px solid #ddd; }
  .summary table { width: 100%; }
  .summary td { vertical-align: top; padding-right: 16px; }
  .s-label { font-size: 8px; text-transform: uppercase; color: #999; margin-bottom: 2px; }
  .s-value { font-size: 15px; font-weight: bold; color: #185FA5; }

  .content { padding: 12px 28px; }
  table.data { width: 100%; border-collapse: collapse; }
  table.data thead tr { background: #185FA5; color: #fff; }
  table.data thead th { padding: 6px 8px; font-size: 9px; text-transform: uppercase; text-align: left; }
  table.data tbody tr.even { background: #f4f6fa; }
  table.data tbody td { padding: 6px 8px; font-size: 10px; border-bottom: 1px solid #eee; }
  .tr { text-align: right; }
  .mono { font-family: monospace; font-size: 9px; }
  .badge { padding: 1px 5px; font-size: 9px; font-weight: bold; border: 1px solid #ccc; color: #555; }
  .badge-green  { border-color: #86efac; color: #166534; background: #dcfce7; }
  .footer { margin-top: 14px; padding: 8px 28px; background: #f4f6fa;
            border-top: 1px solid #ddd; font-size: 9px; color: #aaa; text-align: center; }
</style>
</head>
<body>

{{-- Header --}}
<div class="header">
  <table><tr>
    <td class="logo-cell">
      @if($logoSrc)
        <img src="{{ $logoSrc }}" alt="GSAC" style="height:38px;width:auto;" />
      @else
        <span style="font-size:18px;font-weight:bold;color:#185FA5;">GSAC</span>
      @endif
      <div class="report-sub">Supply &amp; Logistics Division</div>
    </td>
    <td class="title-cell">
      <div class="report-title">{{ strtoupper($typeLabel) }} REPORT</div>
      <div class="report-sub">
        Period: {{ \Carbon\Carbon::parse($from)->format('d M Y') }} — {{ \Carbon\Carbon::parse($to)->format('d M Y') }}
        @if($branch) &nbsp;|&nbsp; Branch: {{ $branch->name }} @endif
      </div>
    </td>
  </tr></table>
</div>

{{-- Meta --}}
<div class="meta">
  <table class="meta-table"><tr>
    <td><div class="meta-label">Report Type</div><div class="meta-value">{{ $typeLabel }}</div></td>
    <td><div class="meta-label">From</div><div class="meta-value">{{ \Carbon\Carbon::parse($from)->format('d M Y') }}</div></td>
    <td><div class="meta-label">To</div><div class="meta-value">{{ \Carbon\Carbon::parse($to)->format('d M Y') }}</div></td>
    <td><div class="meta-label">Branch</div><div class="meta-value">{{ $branch?->name ?? 'All Branches' }}</div></td>
    <td><div class="meta-label">Generated By</div><div class="meta-value">{{ $generatedBy }}</div></td>
    <td><div class="meta-label">Generated At</div><div class="meta-value">{{ $generatedAt }}</div></td>
  </tr></table>
</div>

{{-- Summary --}}
<div class="summary">
  <div class="summary-grid">
    @if($type === 'orders')
      <div class="summary-card">
        <div class="s-label">Total Orders</div>
        <div class="s-value">{{ $summary['count'] }}</div>
      </div>
      <div class="summary-card">
        <div class="s-label">Total Amount</div>
        <div class="s-value">₱{{ number_format($summary['total_amount'], 2) }}</div>
      </div>
      <div class="summary-card">
        <div class="s-label">Total VAT</div>
        <div class="s-value" style="color:#374151">₱{{ number_format($summary['total_tax'], 2) }}</div>
      </div>
      <div class="summary-card">
        <div class="s-label">Pending</div>
        <div class="s-value" style="color:#d97706">{{ $summary['by_status']['pending'] ?? 0 }}</div>
      </div>
    @elseif($type === 'invoices')
      <div class="summary-card">
        <div class="s-label">Total Invoices</div>
        <div class="s-value">{{ $summary['count'] }}</div>
      </div>
      <div class="summary-card">
        <div class="s-label">Total Amount</div>
        <div class="s-value">₱{{ number_format($summary['total_amount'], 2) }}</div>
      </div>
      <div class="summary-card">
        <div class="s-label">Total Discount</div>
        <div class="s-value" style="color:#dc2626">₱{{ number_format($summary['total_discount'], 2) }}</div>
      </div>
      <div class="summary-card">
        <div class="s-label">Total VAT</div>
        <div class="s-value" style="color:#374151">₱{{ number_format($summary['total_tax'], 2) }}</div>
      </div>
    @elseif($type === 'branches')
      <div class="summary-card">
        <div class="s-label">Branches</div>
        <div class="s-value">{{ $summary['count'] }}</div>
      </div>
      <div class="summary-card">
        <div class="s-label">Total Orders</div>
        <div class="s-value">{{ $summary['total_orders'] }}</div>
      </div>
      <div class="summary-card">
        <div class="s-label">Total Amount</div>
        <div class="s-value">₱{{ number_format($summary['total_amount'], 2) }}</div>
      </div>
    @elseif($type === 'form-types')
      <div class="summary-card">
        <div class="s-label">Form Types Used</div>
        <div class="s-value">{{ $summary['count'] }}</div>
      </div>
      <div class="summary-card">
        <div class="s-label">Total Quantity</div>
        <div class="s-value">{{ number_format($summary['total_quantity']) }}</div>
      </div>
      <div class="summary-card">
        <div class="s-label">Total Amount</div>
        <div class="s-value">₱{{ number_format($summary['total_amount'], 2) }}</div>
      </div>
    @elseif($type === 'audit-logs')
      <table style="width:100%;border-collapse:collapse;">
        <tr>
          <td style="padding:0 16px 0 0;border-right:1px solid #e5e7eb;">
            <div class="s-label">Total Movements</div>
            <div class="s-value">{{ $summary['total'] }}</div>
          </td>
          <td style="padding:0 16px;border-right:1px solid #e5e7eb;">
            <div class="s-label">Restocks</div>
            <div class="s-value" style="color:#166534">{{ $summary['restocks'] }}</div>
          </td>
          <td style="padding:0 16px;border-right:1px solid #e5e7eb;">
            <div class="s-label">Adjustments</div>
            <div class="s-value" style="color:#1d4ed8">{{ $summary['adjustments'] }}</div>
          </td>
          <td style="padding:0 16px;border-right:1px solid #e5e7eb;">
            <div class="s-label">Fulfillments</div>
            <div class="s-value" style="color:#7c3aed">{{ $summary['fulfillments'] }}</div>
          </td>
          <td style="padding:0 16px;border-right:1px solid #e5e7eb;">
            <div class="s-label">Units Restocked</div>
            <div class="s-value" style="color:#166534">+{{ number_format($summary['total_restocked']) }}</div>
          </td>
          <td style="padding:0 0 0 16px;">
            <div class="s-label">Units Fulfilled</div>
            <div class="s-value" style="color:#dc2626">−{{ number_format($summary['total_fulfilled']) }}</div>
          </td>
        </tr>
      </table>
    @endif
  </div>
</div>

{{-- Data table --}}
<div class="content">
  @if($type === 'orders')
  <table class="data">
    <thead><tr>
      <th>Reference</th><th>Branch</th><th>Requester</th>
      <th>Status</th><th>Priority</th>
      <th class="tr">Subtotal</th><th class="tr">VAT</th><th class="tr">Total</th><th>Date</th>
    </tr></thead>
    <tbody>
      @forelse($data as $i => $r)
      <tr class="{{ $i % 2 === 1 ? 'even' : '' }}">
        <td class="mono">{{ $r['reference'] }}</td>
        <td>{{ $r['branch'] }}</td>
        <td>{{ $r['requester'] ?? '—' }}</td>
        <td><span class="badge">{{ str_replace('_', ' ', $r['status']) }}</span></td>
        <td>{{ ucfirst($r['priority']) }}</td>
        <td class="tr">₱{{ number_format($r['subtotal'], 2) }}</td>
        <td class="tr">₱{{ number_format($r['tax_amount'], 2) }}</td>
        <td class="tr"><strong>₱{{ number_format($r['total'], 2) }}</strong></td>
        <td>{{ $r['date'] }}</td>
      </tr>
      @empty
      <tr><td colspan="9" style="text-align:center;color:#aaa;padding:20px">No data found.</td></tr>
      @endforelse
    </tbody>
  </table>

  @elseif($type === 'invoices')
  <table class="data">
    <thead><tr>
      <th>Invoice #</th><th>Branch</th><th>Period</th><th>Status</th>
      <th class="tr">Subtotal</th><th class="tr">Discount</th><th class="tr">VAT</th><th class="tr">Total</th><th>Due</th>
    </tr></thead>
    <tbody>
      @forelse($data as $i => $r)
      <tr class="{{ $i % 2 === 1 ? 'even' : '' }}">
        <td class="mono">{{ $r['invoice_number'] }}</td>
        <td>{{ $r['branch'] }}</td>
        <td>{{ $r['billing_period'] }}</td>
        <td><span class="badge badge-gray">{{ $r['status'] }}</span></td>
        <td class="tr">₱{{ number_format($r['subtotal'], 2) }}</td>
        <td class="tr">{{ $r['discount_amount'] > 0 ? '−₱'.number_format($r['discount_amount'],2).' ('.$r['discount_rate'].'%)' : '—' }}</td>
        <td class="tr">₱{{ number_format($r['tax_amount'], 2) }}</td>
        <td class="tr"><strong>₱{{ number_format($r['total'], 2) }}</strong></td>
        <td>{{ $r['due_date'] }}</td>
      </tr>
      @empty
      <tr><td colspan="9" style="text-align:center;color:#aaa;padding:20px">No data found.</td></tr>
      @endforelse
    </tbody>
  </table>

  @elseif($type === 'branches')
  <table class="data">
    <thead><tr>
      <th>Branch</th><th>Code</th>
      <th class="tr">Total Orders</th><th class="tr">Pending</th>
      <th class="tr">Delivered</th><th class="tr">Billed</th>
      <th class="tr">Total Amount</th><th>Status</th>
    </tr></thead>
    <tbody>
      @forelse($data as $i => $r)
      <tr class="{{ $i % 2 === 1 ? 'even' : '' }}">
        <td><strong>{{ $r['branch'] }}</strong></td>
        <td class="mono">{{ $r['code'] }}</td>
        <td class="tr">{{ $r['total_orders'] }}</td>
        <td class="tr" style="color:#d97706">{{ $r['pending_orders'] }}</td>
        <td class="tr" style="color:#1d4ed8">{{ $r['delivered_orders'] }}</td>
        <td class="tr" style="color:#166534">{{ $r['billed_orders'] }}</td>
        <td class="tr"><strong>₱{{ number_format($r['total_amount'], 2) }}</strong></td>
        <td><span class="badge {{ $r['is_active'] ? 'badge-green' : 'badge-gray' }}">
          {{ $r['is_active'] ? 'Active' : 'Inactive' }}
        </span></td>
      </tr>
      @empty
      <tr><td colspan="8" style="text-align:center;color:#aaa;padding:20px">No data found.</td></tr>
      @endforelse
    </tbody>
  </table>

  @elseif($type === 'form-types')
  <table class="data">
    <thead><tr>
      <th>Form Type</th><th>Code</th>
      <th class="tr">Times Ordered</th><th class="tr">Total Qty</th>
      <th class="tr">Avg Unit Price</th><th class="tr">Total Amount</th>
    </tr></thead>
    <tbody>
      @forelse($data as $i => $r)
      <tr class="{{ $i % 2 === 1 ? 'even' : '' }}">
        <td><strong>{{ $r['form_type'] }}</strong></td>
        <td class="mono">{{ $r['code'] }}</td>
        <td class="tr">{{ $r['times_ordered'] }}</td>
        <td class="tr">{{ number_format($r['total_quantity']) }}</td>
        <td class="tr">₱{{ number_format($r['avg_price'], 2) }}</td>
        <td class="tr"><strong>₱{{ number_format($r['total_amount'], 2) }}</strong></td>
      </tr>
      @empty
      <tr><td colspan="6" style="text-align:center;color:#aaa;padding:20px">No data found.</td></tr>
      @endforelse
    </tbody>
  </table>

  @elseif($type === 'audit-logs')
  <table class="data" style="font-size:8px;">
    <thead><tr>
      <th style="width:12%">Date &amp; Time</th>
      <th style="width:18%">Product</th>
      <th style="width:10%">Type</th>
      <th class="tr" style="width:8%">Change</th>
      <th class="tr" style="width:7%">Before</th>
      <th class="tr" style="width:7%">After</th>
      <th style="width:14%">Reference</th>
      <th style="width:16%">Notes</th>
      <th style="width:8%">By</th>
    </tr></thead>
    <tbody>
      @php $typeLabels = ['restock' => 'Restock', 'adjustment' => 'Adjust', 'order_fulfillment' => 'Fulfil']; @endphp
      @forelse($data as $i => $r)
      <tr class="{{ $i % 2 === 1 ? 'even' : '' }}">
        <td class="mono" style="font-size:7.5px;">{{ $r['date'] }}</td>
        <td>
          <strong>{{ $r['product'] ?? '—' }}</strong>
          <span class="mono" style="color:#888;font-size:7px;"> {{ $r['product_code'] }}</span>
        </td>
        <td><span class="badge">{{ $typeLabels[$r['type']] ?? $r['type'] }}</span></td>
        <td class="tr" style="font-weight:bold;color:{{ $r['quantity_change'] >= 0 ? '#166534' : '#dc2626' }};">
          {{ $r['quantity_change'] >= 0 ? '+' : '' }}{{ $r['quantity_change'] }}
        </td>
        <td class="tr">{{ $r['quantity_before'] }}</td>
        <td class="tr"><strong>{{ $r['quantity_after'] }}</strong></td>
        <td class="mono" style="font-size:7.5px;">{{ $r['reference'] ?? '—' }}</td>
        <td style="font-size:7.5px;">{{ Str::limit($r['notes'] ?? '—', 40) }}</td>
        <td style="font-size:7.5px;">{{ $r['performed_by'] ?? '—' }}</td>
      </tr>
      @empty
      <tr><td colspan="9" style="text-align:center;color:#aaa;padding:20px">No audit log entries for this period.</td></tr>
      @endforelse
    </tbody>
  </table>
  @endif
</div>

<div class="footer">
  Generated by {{ $generatedBy }} on {{ $generatedAt }} &nbsp;|&nbsp; GSAC Supply &amp; Logistics Division
</div>

</body>
</html>
